# Conda Environment Setup ----
#  - Using an environment.yml file with conda
#  - Key Terminal Commands:
#
#    conda env create -f conda_environment_setup/environment_setup.yaml
#    conda env update --file conda_environment_setup/environment_setup.yaml --prune
#    conda env export --name python_automation > envname.yml
#    conda env remove --name python_automation
#    conda activate python_automation
#    conda deactivate
#    conda env list

name: python_automation
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      # Core Data
      - numpy==1.20.2
      - pandas==1.3.3
      - pandas_datareader==0.10.0
      - glob==3.10.0

      # EDA
      - pandas-profiling

      # R Data
      - plydata==0.4.3
      - siuba==0.0.24
      - datatable

      # Visualization
      - matplotlib==3.3.4
      - plotnine==0.7.1
      - mizani==0.7.2
      - plotly==4.14.3
      - altair==4.1.0
